name: build and test

on:
push:
branches: -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set_output
        run: echo "::set-output name=example_output::Hello, World!"

      - name: Use output
        run: echo "The output is ${{ needs.build.outputs.example_output }}"
